apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mediawikiapp.name  }}
  labels:
    {{ .Values.mediawikiapp.labels | indent 12 }}
spec:
  replicas: {{ .Values.mediawikiapp.replicaCount }}
  selector:
    matchLabels:
      {{ .Values.mediawikiapp.labels | indent 12 }}
  template:
    metadata:
      labels:
        {{ .Values.mediawikiapp.labels | indent 12 }}
    spec:
      containers:
        - name: {{ .Values.mediawikiapp.name }}
          image: {{ .Values.mediawikiapp.image }}
          imagePullPolicy: {{ .Values.mediawikiapp.pullPolicy }}
          ports:
            - containerPort: 80
