
mediawikiapp:
  name: mediawikiapp-deploy
  labels: |
     app: mediawiki
  image: mwapp.azurecr.io/mediawiki:95
  replicaCount: 2
  pullPolicy: Always
  storageClassName: managed-csi


mediawikisvc:
  name: mediawikiapp-svc
  labels: |
     app: mediawiki
  type: LoadBalancer
  port: 80
  
