
mediawikiapp:
  name: mediawikiapp-deploy
  labels: |
     app: mediawiki
  image: mwapp.azurecr.io/mediawiki:latest
  replicaCount: 2
  pullPolicy: Always


mediawikisvc:
  name: mediawikiapp-svc
  labels: |
     app: mediawiki
  type: LoadBalancer
  port: 80
  
