
MYSQL_DATABASE: mediawikidb
MYSQL_USER: wikiuser


mediawikidb:
  name: mediawikidb-deploy
  labels: |
     db: mediawiki
  image: mariadb
  replicaCount: 2
  pullPolicy: Always  
  storageClassName: managed-csi


service:
  name: mediawikidb-svc
  type: ClusterIP
  port: 3306
  targetport: 3306
