apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mediawikidb.name }}-cfmap
  labels:
    {{ .Values.mediawikidb.labels | indent 12 }}
data:
  MYSQL_DATABASE: {{ .Values.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}